title: creative agency
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#040404'
    - '#e6ddcf'
    - '#999388'
    - '#2f352b'
    - '#53564b'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: kingdom
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.7914894
