name: kingdom
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: creative agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#e6ddcf'
    - '#999388'
    - '#2f352b'
    - '#53564b'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
